### ISSUE TITLE
Unread post count should update in the title tag for us and for stations

### ISSUE THREAD

**Issue by alykat** [nprapps/liveblog-standalone#11]
In the current/old liveblog, when new posts are published, the number of new posts is reflected in the title tag of the parent page — both on NPR.org and on stations. It would be great to port this over to the new liveblog.

May need to adapt the special pym liveblog loader:
https://github.com/nprapps/npr-pym-liveblog-loader

**Comment by thomaswilburn** [comment]
Duplicate of #10
