### ISSUE TITLE
Published / unpublished state (+ highlighting) of a post should update automatically on the preview page

### ISSUE THREAD

**Issue by alykat** [nprapps/liveblog-standalone#31]
Use case: A published post was unpublished. On the preview page, the label for the post's status updated automatically, but the highlighting did not until I manually refreshed the page.

**Comment by thomaswilburn** [comment]
I believe this should actually be fixed via https://github.com/nprapps/liveblog-standalone/blob/master/src/js/liveblog.js#L90
