### ISSUE TITLE
Test "copy link" buttons on station embeds

### ISSUE THREAD

**Issue by alykat** [nprapps/liveblog-standalone#42]
Looked at the Iowa liveblog on KPCC's site, and I'm noticing something odd when I click a "copy link" button: I get the "Copied!" animation and I see the console log message, but the link doesn't actually show up in my clipboard.

Works fine from the standalone liveblog, and also from the embedded liveblog preview page hosted on apps.

It appears to work fine from CPR's test page, though, so I can't chalk this up to being a weird cross-domain issue.

**Comment by thomaswilburn** [comment]
This was a fun one, but turns out to be a simple solution: if the host page is not secure, the guest iframe isn't allowed to access the clipboard. Switching KPCC's staging site to HTTPS makes the copy command work again. I'll mention this to their digital contact.
