### ISSUE TITLE
Post with "continue reading" toggle is expanded (for a while) when loaded via direct link

### ISSUE THREAD

**Issue by alykat** [nprapps/liveblog-standalone#71]
This post on the March 10 liveblog has a "continue reading this post" toggle on it:
https://apps.npr.org/liveblogs/20200310-primaries/#watch-white-women-in-michigan-15

When I accessed it directly (via the liveblog headlines widget), the both the "continue reading" toggle and the hidden content were visible. After a long delay, maybe 30-60 seconds, the hidden content hid itself.

![image](https://user-images.githubusercontent.com/491318/76368171-aefca280-6305-11ea-98be-11f26fe33d4a.png)

**Comment by thomaswilburn** [comment]
Looks like the CSS for that doesn't treat embeds the same as other sibling content. I'll fix.
